### ISSUE TITLE
No module named Quartz.CoreGraphics

### ISSUE THREAD

**Issue by LecJackS** [asingh33/SupervisedChromeTrex#3]
I'm having problems while trying to run main.py

```
$ KERAS_BACKEND=theano python main.py 
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import Quartz.CoreGraphics as CG
ImportError: No module named Quartz.CoreGraphics
```

The setup is an Anaconda environment on Ubuntu with py2.7 installed and the others key requirements (opencv 3, keras 2 and theano 0.9).

Tried to install quartz or pyobjc with no luck. Any idea?

**Comment by LecJackS** [comment]
Oh my! Its supposed to run on OsX. My bad.

**Comment by aalok-sathe** [comment]
Do you happen to know of any equivalent on Ubuntu or Debian-based OSs though?
